alias cmu="cd /mnt/e/CMU"
alias working="cd /mnt/e/Website/PersonalProject"
alias ta="cd /mnt/e/CMU/953/TA_stuff"
alias practice="cd /mnt/d/programming_practice"

alias jc="javac"
alias jv="java"
alias p3="python3"
alias ni="nvim"
alias v="vim"
alias lr="la -r"
